### ISSUE TITLE
Opus encoding fails on short silence FLAC file

### ISSUE THREAD

**Issue by vlakoff** [Chocobo1/opus-tools_win32-build#13]
### Use case

I am converting Musepack files to Opus, with an intermediate conversion to FLAC so that it is supported by the Opus encoder.

### Issue encountered

I encountered a file on which the Opus encoding fails. The file is a manually-created file of 44 seconds of silence.

Archive containing the original Musepack file and the intermediate FLAC file:
[opus_fails_encoding_from_flac.zip](https://github.com/user-attachments/files/17997181/opus_fails_encoding_from_flac.zip)

### Error message

> ERROR: Could not open FLAC stream.
> Error: unsupported input file: X:/11-21 - (silent tracks).flac

### Details

I encounter the error using your latest build (tried both 32-bit and 64-bit):
> opusenc opus-tools 0.2-34-g98f3ddc-dirty (using libopus 1.5.2)

I do **not** encounter the error with the [latest official build](https://opus-codec.org/downloads/) (which BTW is very old and significantly slower):
> opusenc opus-tools 0.2-3-gf5f571b (using libopus 1.3-26-ge85ed772)

Also, I do not encounter the error if converting from WAV instead of FLAC.

**Comment by vlakoff** [comment]
I experimented with a few of your older builds, considering the recentness of your latest build, but I encountered the same error with them as well.

Aside, regarding the official builds: I wasn't using the one listed on the [Downloads page](https://opus-codec.org/downloads/) (Opus 1.3), but a build available on this [release announcement page](https://opus-codec.org/release/stable/2019/04/12/libopus-1_3_1.html) (Opus 1.3.1). Nevertheless, I tried both of these official builds, and I don't encounter the error with either of them.

**Comment by Chocobo1** [comment]
Seems like an upstream issue: https://github.com/xiph/opus-tools/issues/78

**Comment by vlakoff** [comment]
That makes sense. The linked issue points to https://github.com/xiph/opus-tools/commit/5d0ac2030244b33bf12512267fe62ffe831bf105, where the requested buffer size has been increased to a (whopping) 64 KB (the `0x10000`), which is above the filesize of the attached FLAC file, 14.2 KB.

However, the code was expected to support such a scenario. I haven't pinpointed the actual issue yet. If I find more, I'll report them in the upstream issue.
