### ISSUE TITLE
Update to 1.2-alpha

### ISSUE THREAD

**Issue by sergeevabc** [Chocobo1/opus-tools_win32-build#2]
Dear Mike,
Could you be so kind to update binaries as [official site rolled out 1.2a][1] a month ago? 

[1]: http://opus-codec.org/release/dev/2016/11/03/libopus-1_2_alpha.html

**Comment by Chocobo1** [comment]
See: https://github.com/Chocobo1/opus-tools_win32-build/releases/tag/2016.12.12

I focus on Opus stable branch, alphas & betas are not my main concern.

**Comment by sergeevabc** [comment]
Thank you.

**Comment by sergeevabc** [comment]
It seems Xiph [updated] Opus stable branch recently, hooray.

[1]: http://www.rarewares.org/opus.php
