### ISSUE TITLE
Encoding sets the tag "encoder: [...]gf5f571b-dirty"

### ISSUE THREAD

**Issue by Sammala** [Chocobo1/opus-tools_win32-build#3]
Hi there,

when I'm encoding with version 2019.04.13 (opus 1.3.1),  it sets the tag "encoder" to "opusenc from opus-tools 0.2-3-**gf5f571b-dirty**"

Is this how it should be? I previously used the 1.3 build from Mozilla and that one always set this tag to "opusenc from opus-tools 0.2-3-**gf5f571b**"

I did a bit of searching and at least from what I could tell, the _-dirty_ is used in beta builds. And is it right that both 1.3 and 1.3.1 are "opus-tools 0.2-3-_gf5f571b_"?

Thanks!

**Comment by Chocobo1** [comment]
>Is this how it should be? 

Yes as I need to change the path to other libraries and tweak some compile flags.
I can patch it to be hidden but I rather leave it be.

>I previously used the 1.3 build from Mozilla and that one always set this tag to "opusenc from opus-tools 0.2-3-gf5f571b"

They have their own environment and I guess they doesn't need to change the paths nor tweak the compile flags.

>And is it right that both 1.3 and 1.3.1 are "opus-tools 0.2-3-gf5f571b"?

Yes, opus-tools didn't receive any new changes so it stays the same.
