### ISSUE TITLE
opus-tools 2020.07.18 can't run in Windows XP

### ISSUE THREAD

**Issue by Lisabon** [Chocobo1/opus-tools_win32-build#5]
opus-tools 2020.07.18 can't run in Windows XP SP3 32-bit.
![2020-08-07_091849](https://user-images.githubusercontent.com/20801906/89615543-887c6c80-d88f-11ea-81f9-3a4605984b91.png)

**Comment by Chocobo1** [comment]
Unfortunately MSVC 2019 has dropped Windows XP support and IMO Windows XP is really too ancient.
`2019.04.13` is the last version that still supports Windows XP.
I've added notice texts around and stopped mentioning of XP support.
