### ISSUE TITLE
Request: Build version with ML-based features

### ISSUE THREAD

**Issue by 38github** [Chocobo1/opus-tools_win32-build#7]
> [...]all new ML-based features are disabled by default in Opus 1.5. They require both a compile-time switch (for size reasons) and then a run-time switch (for CPU reasons).

Thanks in advance.

**Comment by Chocobo1** [comment]
Already enabled:
https://github.com/Chocobo1/opus-tools_win32-build/blob/9db3af94c527943e69d623f31a7dee2f324957ed/.appveyor.yml#L44
