### ISSUE TITLE
Multiple virus detection warnings for Apr 15 build

### ISSUE THREAD

**Issue by DoulosTrieste** [Chocobo1/opus-tools_win32-build#9]
![image](https://github.com/Chocobo1/opus-tools_win32-build/assets/19621870/19ba1d6f-eb6a-4319-9e95-89dbeeac8e46)

![image](https://github.com/Chocobo1/opus-tools_win32-build/assets/19621870/01066fbe-90e8-47d1-ad50-ed03774ff62d)

![image](https://github.com/Chocobo1/opus-tools_win32-build/assets/19621870/268f0741-2bd5-42e0-a55d-697f7191fb47)

![image](https://github.com/Chocobo1/opus-tools_win32-build/assets/19621870/4d87d25b-84b7-4174-9847-ca1abb01981d)

**Comment by Chocobo1** [comment]
I'm aware of it but sadly I don't know how to improve the situation.

I could build it locally and distribute the executables but would you trust it? Compared to the current open build logs this way is opaque. At this point I would suggest you build the program yourself.

Also see my previous reply: https://github.com/Chocobo1/opus-tools_win32-build/issues/8#issuecomment-2007698239

**Comment by Chocobo1** [comment]
I suppose I could migrate from Appveyor to Github Actions but I'm not sure it will resolve this issue.

**Comment by DoulosTrieste** [comment]
I'm not familiar with the situation and Googling some of these obscure vendor names doesn't provide much useful information. Are they flagging out code obfuscation? And I only became aware of it because Microsoft Defender got triggered and quarantined it right after downloading.

**Comment by Chocobo1** [comment]
>Are they flagging out code obfuscation? 

I don't do obfuscation and I don't think any source code in upstream (opus, etc.) are doing that.
Compression with 7-zip shouldn't get in the way, the code is open source and well known.

>I'm not familiar with the situation and Googling some of these obscure vendor names doesn't provide much useful information.

AFAIK those detection are based on machine learning and maybe the encode/decode routines misled them. I'm not sure.
Another hypothesis is Appveyor might have some 'issues' but there is no concrete evidence and just wild guess at this point.

**Comment by Chocobo1** [comment]
As an experiment, I've just build it on my machine and sent it to virustotal to analyze.

Here is the report: https://www.virustotal.com/gui/file/986216e14629c93527c2e00213771e67d797245114ad094f60bf17af6ef01e19?nocache=1
Here are the executables: [opus_x64.zip](https://github.com/Chocobo1/opus-tools_win32-build/files/15090438/opus_x64.zip)

As you can see there are still false-positives although it is vastly less than the appveyor builds.

**Comment by DoulosTrieste** [comment]
Thanks and apologies for any trouble I caused. It's galling that antivirus engines are compromising themselves and user trust with subpar ML algorithms.
